apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  labels:
    app: web
spec:
  containers:
    - name: jenkins-pod
      image: jenkins/jenkins
      command: ["bash"]
      args: ["-c", "echo this is devops > /tmp/index.txt && sleep 10m"]
      volumeMounts:
        - name: empty
          mountPath: /tmp
  volumes:
    - name: empty
      emptyDir: {}
      
