---
apiVersion: v1
kind: Pod
metadata:
  name: ephemeral-pod
spec:
  containers:
    - name: jenkins
      image: jenkins/jenkins
      command: "bash"
      args: ["-c", "echo this is my laptop > /var/lib/jenkins/index.txt && sleep 5m"]
      volumeMounts:
        - name: ephemeral
          mountPath: "/var/lib/jenkins"
  volumes: 
    - name: ephemeral-volumes
      ephemeral:
        volumeClaimTemplate:
          metadata:
            name: ephemeral-claim
            labels:
              dev: aws
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: "storage-class"
            resources:
              requests: 
                storage: 1Gi

              
