---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonSet-pod
  labels:
    app: aws
spec:
  minReadySeconds: 2
  selector:
    matchLabels:
      dev: env
  template:
    metadata:
      name: daemonSet-node
      labels:
        dev: env
    spec:
      containers:
        - name: daemonSet-jenkins
          image: jenkins/jenkins
          ports:
            - containerPort: 8080
          