---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx
  labels: 
    dev: env
spec:
  minReadySeconds: 3
  replicas: 5
  selector: 
    matchLabels:
      app: aws
  strategy:
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 15%
  template:
    metadata:
      name: nginx-deploy
      labels: 
        app: aws
    spec:
      containers: 
        - name: niginx-pod
          image: nginx
          ports:
            - containerPort: 80
       
##### sirvice file #####


---
apiVersion: v1
kind: Service
metadata:
  name: alpine
spec:
  selector:
    app: aws
  type: LoadBalancer
  ports:
    - port: 80