apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
spec:
  minReadySeconds: 2
  replicas: 4
  serviceName: "nginx-svc"
  selector:
    matchLabels:
      app: nginx
  template: 
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: niginx-home
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: niginx-home
      spec:
        accessModes: 
          - ReadWriteOnce
        resources: 
          requests: 
            storage: 1Gi
        
  
---
apiVersion: v1 
kind:  service 
metadata:
  name: nginx
  labels: 
    app: nginx
spec: 
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80  



  

            

  





    

   