---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nop-replicaset
  labels: 
    qt: env
spec:
  minReadySeconds: 2
  replicas: 4
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: nop-pod
      labels:
        app: web 
    spec:
      containers:
        - name: nop-container
          image: paddutester/nop:nop-10
          ports:
            - containerPort: 5000 